### ISSUE TITLE
vObject 3.0 todo

### ISSUE THREAD

**Issue by evert** [sabre-io/vobject#35]
Todo:
- [x] Change parser to deserialize multiple values
- [x] Property::toString
- [x] Parameter::serialize does not deal with arrays
- [x] Splitters should use streams
- [x] Ability to create a component with a magic setter.
- [x] 100% unittest coverage
- [x] Simplify array access for Parameters. Since they are now indexed by key, a lot of code can be scrapped.
- [x] Go over all vCard 2.1 properties and map them.
- [x] Go over all vCard 3.0 properties and map them.
- [x] Go over all vCard 4.0 properties and map them.
- [x] Go over all iCalendar 2.0 properties and map them.
- [x] Automatically prime new calendars and vcards with default properties.
- [x] Allow `\DateTime` values to be set using setValue()
- [x] Properly test DateTime properties. I suspect that it's broken for some vCard formats.
- [x] Uri needs better serializer/deserializer that doesn't do any escaping.
- [x] Some default value-types have changed in vCard 4. We need to change propertyMap to something that be overridden per vCard versions.
- [x] Issue #40 
- [x] Issue #39 
- [x] Changing properties from `DATE-TIME` to `DATE` as reported on the [mailing list](https://groups.google.com/forum/?hl=en&fromgroups#!topic/sabredav-discuss/kCwOcZ5ZUfg)
